# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SerialMail

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Value(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 3

    # Value
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Value
    def Data0(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Value
    def Data1(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # Value
    def Data2(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateValue(builder, data0, data1, data2):
    builder.Prep(1, 3)
    builder.PrependUint8(data2)
    builder.PrependUint8(data1)
    builder.PrependUint8(data0)
    return builder.Offset()
