# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mail

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Mail(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Mail()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMail(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Mail
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Mail
    def Inputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Mail.Input import Input
            obj = Input()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Mail
    def InputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Mail
    def InputsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Mail
    def Classification(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Mail
    def ClassificationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Mail
    def ClassificationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Mail
    def ClassificationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Mail
    def ClassificationActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Mail
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def MailStart(builder):
    builder.StartObject(4)

def Start(builder):
    MailStart(builder)

def MailAddInputs(builder, inputs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(inputs), 0)

def AddInputs(builder, inputs):
    MailAddInputs(builder, inputs)

def MailStartInputsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputsVector(builder, numElems):
    return MailStartInputsVector(builder, numElems)

def MailAddClassification(builder, classification):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(classification), 0)

def AddClassification(builder, classification):
    MailAddClassification(builder, classification)

def MailStartClassificationVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartClassificationVector(builder, numElems):
    return MailStartClassificationVector(builder, numElems)

def MailAddClassificationActive(builder, classificationActive):
    builder.PrependBoolSlot(2, classificationActive, 0)

def AddClassificationActive(builder, classificationActive):
    MailAddClassificationActive(builder, classificationActive)

def MailAddChannel(builder, channel):
    builder.PrependBoolSlot(3, channel, 0)

def AddChannel(builder, channel):
    MailAddChannel(builder, channel)

def MailEnd(builder):
    return builder.EndObject()

def End(builder):
    return MailEnd(builder)
